# This file is used by `sops` to map the matching file to a public key for encryption.

keys:
  - &mabq age120tq73mkdzyjaq544rs9cqkedetzg6y8tu763ax03zvprg8emq5qnd2az2
  # - &jmsb age1...

creation_rules:
  - path_regex: users/mabq/secrets/secrets.yaml$
    key_groups:
      - age:
          - *mabq
          # - *admin # Can be encrypted for multiple users

  # - path_regex: secrets/jmsb.yaml$
  #   key_groups:
  #     - age:
  #         - *jmsb
