# Zsh as the main shell
{
  dotfiles ? "default",
}:
{
  pkgs,
  user,
  repoDir,
  ...
}:
{
  imports = [
    ./dependencies/bat.nix
    ./dependencies/starship.nix
    ./dependencies/tmux.nix
    ./dependencies/yazi.nix
  ];

  # Must be enabled to be used as the default shell
  programs.zsh.enable = true;

  # Make it the default shell for the user
  users.users.${user}.shell = pkgs.zsh;

  # Home-manager
  home-manager.users.${user} = {
    home = {
      packages = with pkgs; [
        # -- Tools required by aliases and functions --
        exfatprogs # exFAT filesystem userspace utilities
        eza # Modern, maintained replacement for ls (!aliases)
        ffmpeg # Complete, cross-platform solution to record, convert and stream audio and video (!functions)
        fzf # Command-line fuzzy finder
        imagemagick # Software suite to create, edit, compose, or convert bitmap images (!functions(
        parted # Create, destroy, resize, check, and copy partitions
        zoxide # Fast cd command that learns your habits (!aliases) (must be initialized)
        zsh-autosuggestions # Fish-like shell autosuggestions for Zsh (!inputrc)
        zsh-history-substring-search # Fish-like shell history-substring-search for Zsh (!inputrc)
        zsh-syntax-highlighting # Fish-like shell like syntax highlighting for Zsh (!inputrc)
      ];

      # Options and variables specific to zsh (must go in this file)
      file.".zshenv" = {
        text = ''
          ## -- Read notes in zsh nix module --
          setopt NO_GLOBAL_RCS
          ZDOTDIR="${repoDir}/dotfiles/zsh/${dotfiles}"
        '';
        force = true;
      };
    };
  };
}

/*
  Shell Types
  ===========

    - Interactive:      Terminal windows
    - Non-interactive:  Running scripts
    - Login:            Initial login / SSH login

  Verify:

    - Run `echo $0`, if the shell name begins with a hyphen (e.g., `-zsh` or
      `-bash`), it is a login shell.

    - Run `echo $-`, if the output includes the letter `i` (e.g., `58912ilm` or
      `himBHs`), the shell is interactive.

  Config files
  ============

  Zsh uses five main startup configuration files, each serving a specific
  purpose depending on whether the shell is interactive or non-interactive, and
  whether it is a login shell. E.g. `ssh user@ip` starts both a login shell and
  an interactive shell.

  Each file has a system and user-level version. System-level files are shared
  by all users. User-level files have precedence.

  System files are located in `/etc/` and are sourced right before their
  corresponding user-level files. So, the sourcing order is:

      System-wide                  User-level
      ------------------           -------------------
      1. `/etc/zshenv`              2. `~/.zshenv`
      3. `/etc/zprofile`            4. `~/.zprofile`
      5. `/etc/zshrc`               6. `~/.zshrc`
      7. `/etc/zlogin`              8. `~/.zlogin`
      9. `/etc/zlogout`            10. `~/.zlogout`

  zshenv
  ------

  Both `/etc/zshenv` and `~/.zshenv` are ALWAYS sourced.

  Keep these files as lightweight as possible to avoid slowing down script
  execution. Put only environment variables that must be available to all
  scripts, subshells, and applications. Do not put output commands, aliases, or
  prompt configurations here.

  `/etc/zshenv`
    Automatically generated by NixOS with the `programs.zsh.*` options (which
    we don't use). NixOS automatically configures this file to source
    `/etc/set-environment` which contains variables set with the NixOS
    `environment.sessionVariables` option. Do a live grep to see where that
    option is used.

    To learn more see `environment-variables` notes in the learning repo.

  `~/.zshenv`
    Created by this file with the following:

    - `NO_GLOBAL_RCS` option
       Instructs zsh to ignore all sub-sequent system-level configuration
       files. See notes in `zshrc` below.

    - `ZDOTDIR` variable
       Instructs zsh where to find all other user-level zsh configuration
       files. No need to export.

  zprofile
  --------

  Only runs at for login shells. Its primary purpose is to set up the
  environment configuration — such as system-wide environment variables, PATH
  modifications, and startup utilities—that only needs to be defined once per
  login session, rather than every time you open a new terminal window or tab.

  The system-level file generated by NixOS does not contain anything.

  We do not create a user-level version of this file.

  zshrc
  -----

  Runs everytime you open an interactive terminal window. Controls the
  interactive terminal user experience.

  The system-level file generated by NixOS contains zsh configuration options that
  are enabled by default by nix (e.g. `programs.zsh.enableCompletion`). Since we
  set all those options in out zsh config files we do not need to source this
  file, that's why we skip it with `NO_GLOBAL_RCS`.

  All files in ZDOTDIR will be sourced for user interactive shell.

  zlogin
  ------

  Executes commands immediately after the shell environment is fully
  initialized, at login, immediately after `.zshrc`.

  Use for startup status messages, displaying system info (neofetch), or
  launching a window manager.

  zlogout
  -------

  Runs upon exiting a login shell. Used for clearing the terminal screen,
  dropping temporary files, or logging logout times.
*/
