# Zsh as the main shell
{
  pkgs,
  user,
  repoDir,
  themeDir,
  ...
}:
{
  imports = [
    ./dependencies/atuin.nix
    ./dependencies/bat.nix
    ./dependencies/starship.nix
    ./dependencies/tmux.nix
    ./dependencies/yazi.nix
  ];

  # Must be enabled to be used as the default shell
  programs.zsh.enable = true;

  # Make it the default shell for the user
  users.users.${user}.shell = pkgs.zsh;

  environment.sessionVariables = {
    PATH = "${repoDir}/bin:$PATH";
    PAGER = "less -R --use-color -Dd+r -Du+b";
    MANPAGER = "$PAGER";
    MANROFFOPT = "-P -c"; # https://wiki.archlinux.org/title/Color_output_in_console#Using_less
    # TERM=  # Do not set this variable, it is set by each terminal emulator.
  };

  # Home-manager
  home-manager.users.${user} = {
    home = {
      packages = with pkgs; [
        exfatprogs # exFAT filesystem userspace utilities (!functions)
        eza # Modern, maintained replacement for ls (!aliases)
        fd # Simple, fast and user-friendly alternative to find
        ffmpeg # Complete, cross-platform solution to record, convert and stream audio and video (!functions)
        fzf # Command-line fuzzy finder
        imagemagick # Software suite to create, edit, compose, or convert bitmap images (!functions(
        parted # Create, destroy, resize, check, and copy partitions (!functions)
        ripgrep # Utility that combines the usability of The Silver Searcher with the raw speed of grep
        zoxide # Fast cd command that learns your habits (!aliases) (must be initialized)
        zsh-autosuggestions # Fish-like shell autosuggestions for Zsh (!inputrc)
        zsh-history-substring-search # Fish-like shell history-substring-search for Zsh (!inputrc)
        zsh-syntax-highlighting # Fish-like shell like syntax highlighting for Zsh (!inputrc)
      ];

      file.".zshenv" = {
        text = ''
          ## Read notes in zsh nix module
          setopt NO_GLOBAL_RCS
          ZDOTDIR="${repoDir}/config/zsh"
          export REPODIR="${repoDir}"
          export THEMEDIR="${themeDir}"
        '';
        force = true;
      };
    };
  };
}

/*
  Shell Types
  ===========

    - Interactive:      Terminal windows
    - Non-interactive:  Running scripts
    - Login:            Initial login / SSH login

  Config files
  ============

  Zsh uses five main startup configuration files, each serving a specific
  purpose depending on whether the shell is interactive or non-interactive, and
  whether it is a login shell.

     System-level          User-level
     ------------          ----------
   1 `/etc/zshenv`       2 `~/.zshenv`
   3 `/etc/zprofile`     4 `~/.zprofile`
   5 `/etc/zshrc`        6 `~/.zshrc`
   7 `/etc/zlogin`       8 `~/.zlogin`
   9 `/etc/zlogout`     10 `~/.zlogout`

  System-wide versions located in `/etc/` are sourced right before their
  corresponding user-level files. So, `/etc/zshenv`, then `~/.zshenv`, then
  `/etc/zprofile`, then `~/.zprofile` and so on.

  zshenv
  ------

  Read on EVERY shell launch (interactive or non-interactive).

  Keep these files as lightweight as possible to avoid slowing down script
  execution. Put only environment variables that must be available to all
  scripts, subshells, and applications. Do not put output commands, aliases, or
  prompt configurations here.

  The system-level file is automatically generated by NixOS.

    - Sources the file `/etc/set-environment` which is automatically generated
    by NixOS with the environment variables defined in the
    `environment.sessionVariables` NixOS option.
    Bash, Zsh, Fish, etc., source this file during initialization, so you can
    change the default shell and the variables will still be created.

    - Additionally, NixOS runs a service during login (`import-environment`)
    that pushes variables from `/etc/set-environment` into the `systemd --user`
    instance via `systemctl --user import-environment`, meaning those variables
    are also available for systemd user services.

    - Global system daemons (like `sshd`, `nginx`, or `docker`) do not inherit
    those variables. System-level systemd services run in isolated execution
    environments controlled directly by PID 1 (systemd). They do not load
    interactive shell profiles or login session environments for security and
    predictability reasons. If you need to set environment variables for those,
    check the NixOs options:
      `systemd.services.<myservice>.environment`
      `systemd.globalEnvironment`

  The user-level file is created by this module.

    - `NO_GLOBAL_RCS` option
       Instructs zsh to ignore all sub-sequent system-level configuration
       files. They contain configurations that we don't need and may conflict
       with our config.

    - `ZDOTDIR` variable
       Shows zsh where to find all other user-level zsh configuration files.
       No need to export.

    - `REPODIR` variable
       Used by a couple config files to avoid hard-coding the repo directory.
       Must be exported to be available in scripts, e.g. tmux-sessionizer

    - `THEMEDIR` variable
       Used by config files that admit global variables to avoid hard-coding
       the theme path.
       Must be exported to be available in configuration files.

  zprofile
  --------

  Only runs at for login shells. Its primary purpose is to set up the
  environment configuration—such as system-wide environment variables, PATH
  modifications, and startup utilities—that only needs to be defined once per
  login session, rather than every time you open a new terminal window or tab.

  zshrc
  -----

  Runs everytime you open an interactive terminal window. Controls the
  interactive terminal user experience.

  Place all your prompt settings (e.g., Starship, Oh My Zsh), interactive
  options (setopt), completion setup (compinit), aliases, and custom functions
  here.

  zlogin
  ------

  Executes commands immediately after the shell environment is fully
  initialized, at login, immediately after `.zshrc`.

  Use for startup status messages, displaying system info (neofetch), or
  launching a window manager.

  zlogout
  -------

  Runs upon exiting a login shell. Used for clearing the terminal screen,
  dropping temporary files, or logging logout times.
*/
