# [Theme]
# # Color palettes and UI styling (Gtk/Waybar sync)
# theme_name = Catppuccin-Mocha
# cursor_theme = Bibata-Modern-Ice
# cursor_size = 24
# font_name = JetBrainsMono Nerd Font 11

# # Hex colors for borders and UI elements
# color_active_border = 0xffcba6f7
# color_inactive_border = 0xff313244
# color_background = 0xff1e1e2e

background = 0xFF1E1E2E
base = 0xFF313244
text = 0xFFCDD6F4
alternate_base = 0xFF45475A
bright_text = 0xFFFFDEDE
accent = 0xFF89B4FA
accent_secondary = 0xFFCBA6F7
h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10
icon_theme = Papirus-Dark
font_family = JetBrainsMono Nerd Font
font_family_monospace = monospace
rounding_large = 0
rounding_small = 0
