# -----------------------------------------------------------------------------
# Replace UUIDs with labels:
#   - `/boot`  ->  `/dev/disk/by-label/boot`
#   - `/`      ->  `/dev/disk/by-label/nixos`
#
# Check swap info after installation
# -----------------------------------------------------------------------------

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "ehci_pci"
    "ahci"
    "firewire_ohci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # --------------------------------------------------------------------------
  # WARNING! Check this after installation
  # --------------------------------------------------------------------------
  boot.initrd.luks.devices."luks-cb062bd9-012e-4bfe-ba85-05c85c07d7dc".device =
    "/dev/disk/by-uuid/cb062bd9-012e-4bfe-ba85-05c85c07d7dc";
  boot.initrd.luks.devices."luks-549311fe-99eb-49e1-a092-d41c8c5a21e8".device =
    "/dev/disk/by-uuid/549311fe-99eb-49e1-a092-d41c8c5a21e8";

  swapDevices =
    [{ device = "/dev/disk/by-uuid/a0949e2f-40f5-480d-a42f-44d77cecefbc"; }];

  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
